# Generated by Django 5.1.4 on 2025-01-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon_users', '0003_servicecategory_add_to_home_services_add_to_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_categories/'),
        ),
    ]
