# Generated by Django 5.1.4 on 2025-01-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon_users', '0006_service_is_active_alter_service_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='add_to_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/service_categories/'),
        ),
    ]
