# Generated by Django 5.1.4 on 2025-01-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon_users', '0008_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_role',
            field=models.CharField(choices=[('customer', 'Customer'), ('staff', 'Staff'), ('admin', 'Admin'), ('manager', 'Manager')], default='customer', max_length=20),
        ),
    ]
