# Generated by Django 5.1.4 on 2025-01-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon_users', '0009_userprofile_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='static/blogs/'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
