# Generated by Django 5.1.4 on 2025-02-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon_users', '0010_alter_blog_image_alter_reviews_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='blogs/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_categories/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
